version: "3.3"
services:

  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    networks:
      - default
      - openlmis-ref-distro_default
    environment:
     - BOOTSTRAP_SERVERS=kafka:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - HOST_NAME=0.0.0.0

networks:
  openlmis-ref-distro_default:
    external: true
