#!/bin/bash

# Usage:
# First argument - username
# Second argument - database host
# Third argument - database port
# Fourth argument - database name
# Fifth argument - password

OLDPGPASSWORD=$PGPASSWORD
export PGPASSWORD=$5;

COMMAND="UPDATE auth.oauth_client_details SET resourceids = resourceids || ',reports' where clientid IS NOT NULL";

psql -U "$1" -h "$2" -p "$3" -d "$4" -t -c "$COMMAND"

export PGPASSWORD=$OLDPGPASSWORD;
