#!/bin/bash

# Usage:
# First argument - username
# Second argument - database host
# Third argument - database port
# Fourth argument - database name

COMMAND="UPDATE auth.oauth_client_details SET resourceids = resourceids || ',reports' where (clientid = 'trusted-client' or clientid = 'user-client')";

psql -U "$1" -h "$2" -p "$3" -d "$4" -W -t -c "$COMMAND"
